version: "3.5"

services:
  db:
    container_name: "db"
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=arhvp
      - POSTGRES_PASSWORD=arhvp
      - POSTGRES_DB=arhvp
    ports:
      - "5432:5432"
    networks:
      - custom


networks:
  custom:
    driver: bridge
