"""rename column Users

Revision ID: 63e305e0418e
Revises: 2857335768c5
Create Date: 2023-09-16 14:16:59.015194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63e305e0418e'
down_revision: Union[str, None] = '2857335768c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registered_at', sa.TIMESTAMP(), nullable=True))
    op.drop_column('users', 'regastared_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('regastared_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'registered_at')
    # ### end Alembic commands ###
